name: Docker build and Push 
on:
  workflow_call:
    secrets:
      GHCR_PAT:
        required: false

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps: 
      - name: Checkout repositry 
        uses: actions/checkout@v2

      - name: Login Github Container D
        run: echo "${{ secrets.GHCR_PAT }}" | sudo docker login ghcr.io -u hsein1bourgi --password-stdin
     
      - name: Install npm dependencies
        run: sudo apt-get update && sudo apt install npm 

      - name: Initiate ndoe.js
        if: success()
        run: npm init -y
        
      - name: Docker Build Image
        run: sudo docker build -t ghcr.io/hsein1bourgi/practical-w:latest .

      - name: Push Docker image to GHCR 
        run: sudo docker push ghcr.io/hsein1bourgi/practical-w:latest

    
   
