name: CI Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y pass gnupg2

      - name: Configure Docker to use pass
        run: |
          echo "{\"credsStore\":\"pass\"}" > ~/.docker/config.json
          gpg --batch --gen-key <<EOF
          %no-protection
          Key-Type: RSA
          Key-Length: 2048
          Subkey-Type: RSA
          Subkey-Length: 2048
          Name-Real: Docker
          Name-Email: docker@example.com
          Expire-Date: 0
          EOF
          gpg --list-secret-keys --keyid-format LONG
          pass init "docker@example.com"

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Convert username to lowercase
        id: to-lower
        run: echo "username=$(echo ${{ github.actor }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ env.username }}/practical-w:latest .

      - name: Push Docker image to GHCR
        run: docker push ghcr.io/${{ env.username }}/practical-w:latest

