name: CI Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Ensure Docker is Running
        run: sudo systemctl start docker

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}

      - name: Build Docker image
        run: sudo docker build -t ghcr.io/hsein1bourgi/practical-w:latest .

      - name: Push Docker image to GHCR
        run: sudo docker push ghcr.io/hsein1bourgi/practical-w:latest
